-- Valeur par défaut
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (115, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (116, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (117, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (118, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (119, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (120, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (121, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (122, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (77, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (123, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (124, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (125, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (126, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (82, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (83, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (84, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (146, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (147, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (148, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (151, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (152, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (153, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (154, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (110, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (111, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (87, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (88, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (103, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (149, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (150, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (89, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (90, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (91, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (92, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (93, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (94, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (95, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (96, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (97, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (98, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (99, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (100, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (168, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (160, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (86, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (161, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (162, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (78, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (79, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (112, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (113, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (114, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (157, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (158, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (104, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (159, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (105, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (106, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (107, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (108, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (109, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (134, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (80, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (127, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (128, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (129, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (130, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (131, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (132, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (133, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (163, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (164, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (165, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (166, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (167, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (135, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (140, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (141, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (142, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (143, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (144, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (145, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (136, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (137, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (138, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (139, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (169, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (170, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (101, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (102, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (75, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (76, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (155, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (156, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (85, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (81, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (175, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (172, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (173, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (174, 'no_all');
INSERT INTO parametres ("departementId", "superpositionCommune") VALUES (176, 'no_all');

-- Valeur remontée par les DDT
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 115;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 116;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 117;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 118;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 120;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 121;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 122;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 77;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 123;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 124;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 125;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 126;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 82;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 83;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 84;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 146;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 147;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 148;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 151;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 152;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 153;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 154;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 87;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 88;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 103;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 149;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 150;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 89;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 90;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 91;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 93;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 94;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 95;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 96;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 97;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 98;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 99;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 100;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 168;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 160;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 86;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 161;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 162;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 78;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 79;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 112;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 113;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 114;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 157;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 158;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 104;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 159;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 105;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 106;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 107;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 109;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 134;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 80;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 127;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 128;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 129;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 132;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 163;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 164;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 165;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 166;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 167;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 135;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 140;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 141;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 142;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 143;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 145;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 136;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 138;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 139;
UPDATE parametres SET "superpositionCommune" = 'yes_only_aep'  where "departementId" = 169;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 170;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 101;
UPDATE parametres SET "superpositionCommune" = 'yes_distinct'  where "departementId" = 102;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 75;
UPDATE parametres SET "superpositionCommune" = 'yes_except_aep'  where "departementId" = 76;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 155;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 156;
UPDATE parametres SET "superpositionCommune" = 'yes_all'  where "departementId" = 85;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 81;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 175;
UPDATE parametres SET "superpositionCommune" = 'no_all'  where "departementId" = 172;
UPDATE parametres SET "superpositionCommune" = 'no'  where "departementId" = 176;
